namespace: jellyfin

resources:
- ../../base

patches:
- path: deployment-patch.yml
  target: 
    group: apps
    version: v1
    kind: Deployment
    name: jellyfin-deployment

# - path: service-patch.yml
#   target: 
#     version: v1
#     kind: Service
#     name: jellyfin-service

# patchesStrategicMerge:
#   - delete-ingress-patch.yml
