namespace: jellyfin

resources:
- ../../base

patches:
- path: deployment-patch.yml
  target: 
    group: apps
    version: v1
    kind: Deployment
    name: jellyfin-deployment

- path: secret-provider-class-patch.yml
  target: 
    group: secrets-store.csi.x-k8s.io
    version: v1alpha1
    kind: SecretProviderClass
    name: csi-key-vault-jellyfin-service

- path: service-patch.yml
  target: 
    version: v1
    kind: Service
    name: jellyfin-service

patchesStrategicMerge:
  - ingress-patch.yml
